ldap lib: support NS7 and NS8 schemas
Avoid error when accessing NS7 LDAP:
 ldap3.core.exceptions.LDAPAttributeError: invalid attribute type pwdAccountLockedTime

Fix regression introduced by 601190a6ec66461bf7fc989269df6e72064ce24d